import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";

import {
  validateLock,
  verifyDigest,
  verifyGeneratedContent,
  verifySourceCheckout
} from "./sync-market-go-client.mjs";

test("Market client sync requires the pinned provider commit", (t) => {
  const checkout = mkdtempSync(join(tmpdir(), "tutti-market-source-"));
  t.after(() => rmSync(checkout, { recursive: true, force: true }));
  execFileSync("git", ["init", "--quiet", checkout]);
  execFileSync(
    "git",
    [
      "-C",
      checkout,
      "commit",
      "--allow-empty",
      "--quiet",
      "-m",
      "provider fixture"
    ],
    {
      env: {
        ...process.env,
        GIT_AUTHOR_EMAIL: "market-client-test@example.invalid",
        GIT_AUTHOR_NAME: "Market Client Test",
        GIT_COMMITTER_EMAIL: "market-client-test@example.invalid",
        GIT_COMMITTER_NAME: "Market Client Test"
      }
    }
  );
  const actualCommit = execFileSync(
    "git",
    ["-C", checkout, "rev-parse", "HEAD"],
    { encoding: "utf8" }
  ).trim();

  assert.doesNotThrow(() => verifySourceCheckout(checkout, actualCommit));
  assert.throws(
    () =>
      verifySourceCheckout(
        checkout,
        "0000000000000000000000000000000000000000"
      ),
    /expected 0000000000000000000000000000000000000000/u
  );
});

test("Market client sync rejects generated output that drifts from its pinned digest", () => {
  const pinned = Buffer.from("generated market client\n");
  const file = {
    sha256: createHash("sha256").update(pinned).digest("hex"),
    source: "api/sandbox/v1/market.pb.go"
  };

  assert.doesNotThrow(() => verifyDigest(file, pinned, "generated target"));
  assert.throws(
    () =>
      verifyDigest(
        file,
        Buffer.from("handwritten market client\n"),
        "generated target"
      ),
    /generated target .* has SHA-256 .* expected/u
  );
});

test("Market client source lock requires immutable commit, paths, and digests", () => {
  const valid = {
    schemaVersion: 1,
    repository: "https://github.com/tutti-lab/tsh-server",
    commit: "a".repeat(40),
    files: [
      {
        source: "api/sandbox/v1/market.pb.go",
        target: "packages/clients/market-go/generated/sandbox/v1/market.pb.go",
        sha256: "b".repeat(64)
      }
    ]
  };

  assert.doesNotThrow(() => validateLock(valid));
  assert.throws(
    () => validateLock({ ...valid, commit: "main" }),
    /full Git SHA/u
  );
  assert.throws(
    () =>
      validateLock({
        ...valid,
        files: [{ ...valid.files[0], target: "../handwritten.go" }]
      }),
    /Invalid Market client target path/u
  );
  assert.throws(
    () =>
      validateLock({
        ...valid,
        files: [{ ...valid.files[0], sha256: "changed" }]
      }),
    /Invalid Market client SHA-256/u
  );
});

test("Market wire targets cannot replace generated code with handwritten DTOs", () => {
  const file = {
    source: "api/sandbox/v1/market.pb.go",
    target: "packages/clients/market-go/generated/sandbox/v1/market.pb.go"
  };
  assert.doesNotThrow(() =>
    verifyGeneratedContent(
      file,
      Buffer.from("// Code generated by protoc-gen-go. DO NOT EDIT.\n")
    )
  );
  assert.throws(
    () =>
      verifyGeneratedContent(
        file,
        Buffer.from("package v1 // handwritten MarketResponse\n")
      ),
    /is not generated code/u
  );
});
